version: '2'

services:
    web:
        build: .
        working_dir: /usr/src/app/
        command: python -u server.py
        ports:
            - 8888:8888
        volumes:
            - .:/home/src/app/
        env_file:
            - .env