version: '2.4'

services:
    web:
        restart: always
        build: .
        working_dir: /usr/src/app/
        command: python -u server.py
        init: true
        ports:
            - 8888:8888
        volumes:
            - .:/home/src/app/
        env_file:
            - .env
